version: "v1"

http:
  listener:
    basePath: "/a-country-weather-pa/api/${version}"
  requester:
    countryWeatherAPI:
      basePath: "/a-country-weather-sa/api/v1"
    mongodbAPI:
      basePath: "/a-mongodb-sa/api/v1"

rabbitMQ:
  exchange: "country.city.topic"
  queue: "country.city.queue"
  routingKey: "*.*.updated"
  deadLetterQueue: "country.city.dlq"
  
log:
  dir: "![aIU7YR+b/5wNP4kgLrf258t4CtMq/BGWIQy92rhidXFZG/6kxl0QEw43xeZPCx/jGFuyFn3ZuEY=]"